---
title: "Create simulated data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(zipcodeR)
data("zip_code_db")
```

get data
```{r}
input_df <- read_excel("data/ALAI UP Client-level Reporting Tool_short_template_2.26.26.xlsx",
                       sheet = "Client-level data")

input_df[1:1000,] <- NA

ny_zips <- zip_code_db |>
  filter(county == "New York County",
         !is.na(lat))

set.seed(123)
```

```{r}
n = 1000
df <- input_df |>
  mutate(site = "My site",
         alai_up_uid = row_number(),
         zip_code = sample(ny_zips$zipcode,n, replace = T),
         age = round(truncnorm::rtruncnorm(n, a = 18, b = 90, mean = 42, sd = 13)),
         birth_year = 2025 - age,
         ethnicity_hispanic = rbinom(n,1,0.2),
         race = sample(x = c("ai_an","asian","black","nh_pi","white","other"),
                       size = n,
                       replace = TRUE,
                       prob = c(0.005,0.02,0.53,0.005,0.37,0.07)),
         race_ai_an = if_else(race == "ai_an",1,0),
         race_asian = if_else(race == "asian",1,0),
         race_black = if_else(race == "black",1,0),
         race_nh_pi = if_else(race == "nh_pi",1,0),
         race_white = if_else(race == "white",1,0),
         race_other = if_else(race == "other",1,0),
         sex_birth = rbinom(n,1,0.22) + 1, # 1 for male, 2 for female
         gender_id = case_when(
           sex_birth == 1 ~ sample(x = c(1,3,5),size = n,replace = T, prob = c(0.95,0.04,0.01)),
           sex_birth == 2 ~ sample(x = c(2,4,5),size = n,replace = T, prob = c(0.95,0.04,0.01))
         ),
         active_2021 = rbinom(n,1,0.8),
         active_2022 = rbinom(n,1,0.85),
         active_2023 = rbinom(n,1,0.9),
         active_2024 = rbinom(n,1,0.95),
         active_2025 = rbinom(n,1,0.95),
         risk_msm = rbinom(n,1,0.6),
         risk_idu = rbinom(n,1,0.1),
         risk_heterosex = rbinom(n,1,0.3),
         insurance_status = sample(x = c(1,2,3,4,5,6,7,8,NA),size = n, replace = T,
                                   prob = c(0.15,0.25,0.1,0.05,0.01,0.01,0.01,0.4,0.02)),
         housing_status = sample(x = c(1,2,3,NA),size = n, replace = T,
                                 prob = c(0.8,0.1,0.05,0.05)),
         employment_status = sample(x = c(1,2,3,NA),size= n, replace = T,
                                     prob = c(0.8,0.1,0.05,0.05)),
         poverty_level = sample(x = c(1,2,3,4,NA), size = n, replace = T),
         immigration_status_undoc = sample(x = c(0,1,NA), size = n, replace = T,
                                           prob = c(0.8,0.1,0.1)),
         language = sample(x = c(1,2,3,4,5,6,7,8,20,NA),size = n, replace = T,
                           prob = c(0.91,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01)),
         incarceration_history = sample(x = c(0,1,2,3,NA), size = n, replace = T,
                                        prob = c(0.8,0.05,0.05,0.05,0.05)),
         cd4_recent_result = truncnorm::rtruncnorm(n, a = 0, b = 1500, mean = 650, sd = 200),
         # counseling and screening
         # ever and never
         icab_rpv_counsel_ever = rbinom(n,1,0.6),
         icab_rpv_screen_ever = case_when(
           icab_rpv_counsel_ever == 1 ~ icab_rpv_counsel_ever - rbinom(n,1,0.05),
           icab_rpv_counsel_ever == 0 ~ icab_rpv_counsel_ever + rbinom(n,1,0.05)
         ),
         # set a ref_date
         ref_date = sample(x = seq(as.Date("2024-01-01"),as.Date("2024-10-31"),by = "day"),
                           size = n, replace = T),
         num_counsel = 1 + rbinom(n,1,0.5),
         #counsel 1 block
         icab_rpv_counsel_1_date = case_when(
           icab_rpv_counsel_ever == 1 ~ ref_date - runif(n,180,360),
           .default = NA
         ),
         icab_rpv_counsel_1_outcome = case_when(
           icab_rpv_counsel_ever == 1 ~ sample(x = c(1,2,3), size = n, replace = T,
                                               prob = c(0.5,0.25,0.25)),
           .default = NA
         ),
         icab_rpv_disinterest_reason_1 = case_when(
           icab_rpv_counsel_1_outcome != 3 ~ sample(x = c(1,2,3,4,5,6,20,NA),size = n, replace = T,
                                                    prob = c(0.6,0.1,0.06,0.04,0.04,0.01,0.1,0.05)),
           .default = NA
         ),
         #counsel 2 block
         icab_rpv_counsel_2_date = case_when(
           icab_rpv_counsel_ever == 1 & num_counsel == 2 ~ ref_date - runif(n,90,180),
           .default = NA
         ),
         icab_rpv_counsel_2_outcome = case_when(
           icab_rpv_counsel_ever == 1 & num_counsel == 2 ~ sample(x = c(1,2,3), size = n, replace = T,
                                               prob = c(0.5,0.25,0.25)),
           .default = NA
         ),
         icab_rpv_disinterest_reason_2 = case_when(
           icab_rpv_counsel_2_outcome == 0 ~ sample(x = c(1,2,3,4,5,6,20,NA),size = n, replace = T,
                                                    prob = c(0.6,0.1,0.06,0.04,0.04,0.01,0.1,0.05)),
           .default = NA
         ),
         #screen 1 block
         icab_rpv_screen_1_date = case_when(
           icab_rpv_screen_ever == 1 ~ ref_date - runif(n,180,360),
           .default = NA
         ),
         icab_rpv_screen_1_outcome = case_when(
           icab_rpv_screen_ever == 1 ~ sample(x = c(0,1), size = n, replace = T,
                                               prob = c(0.7,0.3)),
           .default = NA
         ),
         icab_rpv_not_elig_1_reason = case_when(
           icab_rpv_screen_1_outcome == 0 ~ sample(x = c(1,2,3,4,5,6,7,8,20,NA),size = n, replace = T,
                                                    prob = c(0.6,0.1,0.06,0.04,0.04,
                                                             0.01,0.03,0.03,0.04,0.05)),
           .default = NA
         ),
         #screen 2 block
         icab_rpv_screen_2_date = case_when(
           icab_rpv_screen_ever == 1 & num_counsel == 2 ~ ref_date - runif(n,90,180),
           .default = NA
         ),
         icab_rpv_screen_2_outcome = case_when(
           icab_rpv_screen_ever == 1 & num_counsel == 2 ~ sample(x = c(0,1), size = n, replace = T,
                                               prob = c(0.7,0.3)),
           .default = NA
         ),
         icab_rpv_not_elig_2_reason = case_when(
           icab_rpv_screen_2_outcome == 0 ~ sample(x = c(1,2,3,4,5,6,7,8,20,NA),size = n, replace = T,
                                                    prob = c(0.6,0.1,0.06,0.04,0.04,
                                                             0.01,0.03,0.03,0.04,0.05)),
           .default = NA
         ),
         # rx 
         icab_rpv_rx = case_when(
           num_counsel == 1 & icab_rpv_counsel_1_outcome == 3 & icab_rpv_screen_1_outcome == 1 ~ rbinom(n,1,0.98),
           num_counsel == 2 & icab_rpv_counsel_2_outcome == 3 & icab_rpv_screen_2_outcome == 1 ~ rbinom(n,1,0.98)),
         icab_rpv_rx_date = if_else(icab_rpv_rx == 1, ref_date - runif(n,60,90),NA),
         
         # icab shots
         num_shots = if_else(icab_rpv_rx == 1,sample(seq(2,20,by = 1),size = n, replace = T),NA),
         
         # discontinuation
         icab_rpv_discontinued = if_else(icab_rpv_rx == 1, rbinom(n,1,0.2),NA),
         icab_rpv_discontinued_reason = if_else(icab_rpv_discontinued ==1,
                                                sample(x = c(1,2,3,4,5,6,7,8,9,10,20), size = n, replace = T),
                                                NA),
         
         # hiv vl
         num_vls = sample(seq(7,10),size = n, replace = T)
         )
```


cab doses
```{r}
cab_doses <- df |>
  select(alai_up_uid,contains("icab_rpv_shot"),num_shots,ref_date) |>
  pivot_longer(cols = contains("icab_rpv_shot"),
               names_to = c("index",".value"),
               names_pattern = "icab_rpv_shot(\\d+)_(date|dose)") |>
  mutate(index = as.numeric(index),
         date = as.Date(date)) |>
  arrange(alai_up_uid, index) |>
  mutate(.by = alai_up_uid,
         dose = if_else(any(!is.na(num_shots)),
                        sample(c(1,2),1,replace = T),
                        NA),
         date = case_when(
           !is.na(num_shots) & dose == 1 ~ {
             out <- c(first(ref_date),first(ref_date) + rnorm(1,30,5))
             d <- out[2]
             for (i in 3:n()){
               d <- d + rnorm(1,30,5)
               out <- c(out,d)
             }
             out
           },
           !is.na(num_shots) & dose == 2 ~  {
             out <- c(first(ref_date),first(ref_date) + rnorm(1,30,5))
             d <- out[2]
             for (i in 3:n()){
               d <- d + rnorm(1,60,6)
               out <- c(out,d)
             }
             out
           }
  )) |>
  mutate(dose = if_else(index > num_shots,NA,dose),
         date = if_else(index > num_shots,NA,date)) |> 
  pivot_wider(names_from = "index",
              values_from = c("date","dose"),
              names_glue = "icab_rpv_shot{index}_{.value}") 
```

viral loads
```{r}
vl_df <- df |>
  select(alai_up_uid,contains("hiv_vl")&!contains("dx")&!contains("pre"),num_vls,ref_date) |>
  pivot_longer(cols = contains("hiv_vl"),
               names_to = c("index",".value"),
               names_pattern = "hiv_vl_(\\d+)_(date|dose)") |>
  mutate(index = as.numeric(index),
         date = as.Date(date)) |>
  arrange(alai_up_uid, index) |>
  mutate(.by = alai_up_uid,
         result = if_else(any(!is.na(num_vls)),
                          sample(c(1,2,3,4,5,6),1,replace = T, 
                                 prob = c(0.7,0.1,0.05,0.07,0.04,0.04)),
                          NA),
         date = if_else(
           !is.na(num_vls), {
             out <- c(first(ref_date))
             d <- out[1]
             for (i in 2:n()){
               d <- d + rnorm(1,90,10)
               out <- c(out,d)
             }
             out
           }, NA)) |>
  filter(!is.na(index)) |>
  mutate(result = if_else(index > num_vls,NA,result),
         date = if_else(index > num_vls,NA,date)) |>
  mutate(.by = alai_up_uid,
         max_cab_date = max(date,na.rm = T)) |> 
  pivot_wider(names_from = "index",
              values_from = c("date","result"),
              names_glue = "hiv_vl_{index}_{.value}") 
```



Join cab doses and vl back to data
```{r}
filled_df <- df |>
  select(!contains("icab_rpv_shot")) |>
  full_join(cab_doses) |>
  select(!(contains("hiv_vl")&!contains("dx")&!contains("pre"))) |>
  full_join(vl_df) |>
  # add pre_icab_vl and discontinued date
  mutate(hiv_vl_pre_icab_date = icab_rpv_shot1_date,
         hiv_vl_pre_icab_result = if_else(!is.na(hiv_vl_pre_icab_date),
                                          sample(c(1,2,3,4,5,6),1,replace = T,
                                                 prob = c(0.8,0.1,0.05,0.03,0.01,0.01)),
                                          NA),
         icab_rpv_discontinued_date = if_else(icab_rpv_discontinued == 1,
                                              max_cab_date + 30,
                                              NA)) |>
  select(names(input_df))
```

write to dataframe
```{r}
writexl::write_xlsx(filled_df,
                    path = "data/simulated_data.xlsx")
```







